version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify runtime if needed
  pre_build:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the application..."
  post_build:
    commands:
      - echo "Build completed!"
