#!/usr/bin/env bash
echo "== deploy codebuild via cloud formation CFN"

STACK_NAME="cfn-codebuild-simple"

aws cloudformation deploy \
--template-file template.yaml \
--stack-name $STACK_NAME

# --no-execute-changeset \
