#!/usr/bin/env bash
echo "== Sync"
# exit if an error happened
set -e

# Check if the first argument is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. my-bucket-name"
    exit 1
fi

# Check if filename prefix is provided
if [ -z "$2" ]; then
    echo "There needs to be a filename prefix"
    exit 1
fi

BUCKET_NAME=$1

FILENAME_PREFIX=$2

# where we'll store these filawses
OUTPUT_DIR="/tmp/s3-bash-scripts"

# remove folder if it already exists
# rm -r $OUTPUT_DIR

# lets create output folder
mkdir -p $OUTPUT_DIR


# generate a random number
# to determine-how many files to create
NUM_FILES=$((RANDOM % 6+5))

for ((i=1; i<=$NUM_FILES; i++)); do
# Generate a random filename
FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

#.Generate.random.data.and.write.it.to the.file
dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 +1)) 2>/dev/null
done


aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files