#!/usr/bin/env bash
echo "== delete a bucket:" $1

# Check if the first argument is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name eg. my-bucket-name"
    exit 1
fi

# https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html
aws s3api delete-bucket \
--bucket $1 