#!/usr/bin/env bash

OUTPUT_DIR="/tmp/s3-bash-scripts"

# Create nesseceary folders
mkdir -p $OUTPUT_DIR

# Generate a random number between 5 and 10
NUM_FILES=$( (RANDOM % 6 + 5))

echo "Creating $NUM_FILES random files ... "

for ((i=1; i <= $NUM_FILES; i++)); do
# Generate a random filename
FILENAME="$OUTPUT_DIR/file_$i.txt"

# Generate random data and write it to the file
dd if=/dev/urandom of="$FILENAME" bs=1024 count=$( (RANDOM % 1024 + 1)) 2>/

done