#!/usr/bin/env bash
echo "== deploy msk via cloud formation CFN"

STACK_NAME="cfn-msk-configuration-simple-2"

aws cloudformation deploy \
--template-file config-template.yaml \
--stack-name $STACK_NAME

# --no-execute-changeset \
