AWSTemplateFormatVersion: "2010-09-09"
Description: A simple s3 bucket
Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
  S3Bucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
    Properties:
      BucketName: my-habib-bucket # this is not mandatory AWS creates a random bucket name
